### ISSUE TITLE
Remove use of Python requests library in jbossnetwork API interaction

### ISSUE THREAD

**Issue by sabre1041** [ansible-middleware/common#15]
The interaction with the jbossnetwork API makes use of the Python [requests](https://pypi.org/project/requests) library.

Ansible modules [includes libraries for interacting with URL](https://docs.ansible.com/ansible/latest/dev_guide/developing_module_utilities.html) based targets and would eliminate the need to include external dependencies.

Migrate jbossnetwork api modules from requests to native Ansible module_utils to interact with HTTP/HTTPS based queries

**Comment by guidograzioli** [comment]
Thanks for the PR
